### ISSUE TITLE
Failed to discover root

### ISSUE THREAD

**Issue by dewiweb** [bitfocus/companion-module-riedel-mediornet#1]
Companion version :3.0.0 (3.0.0+5763-beta-4053fafd)
error in log: Instance/Wrapper/mediornet: Failed to discover root: TypeError: Cannot read properties of undefined (reading 'identifier')

**Comment by dewiweb** [comment]
Device: micronUHD
Firmware: latest published by Riedel( think is 7.3.1)
Ember+ enabled
Emberplusview returns matrices populated.

**Comment by Nico96R** [comment]
well strange...
tested the module with exactly this configuration.
MicroN UHD, 7.3.1
Therefore I have trouble reproducing the problem.
I created a new branch and added a console.log command. Could you implement the new version via the module_dev functionality of companion?

The error means, that it couldn't fetch the root of ember+ tree.
Could you also send me a screenshot of your EmBER+ Viewer?

Hopefully we can resolve this issue together.

**Comment by dewiweb** [comment]
Maybe a network issue, not sure. I deleted the first created module's connection and created a new one and it was working like a charm.all works now I made a 130x130 video matrice and I'm able two create/delete connections and retrieve I/O names with feedbacks( I'm using the public release)
