### ISSUE TITLE
Feature Request: Delete Connection

### ISSUE THREAD

**Issue by chownchownchown** [bitfocus/companion-module-riedel-mediornet#6]
Hello, 

Would it be possible to extend the plugin so that existing connections (on video destinations) can be deleted?

Robin

**Comment by Nico96R** [comment]
Hey Robin,

thanks for your feature request. What are you looking for exactly?

- **Delete the connection to one specific destination?** This is already possible by selecting the source "Delete connection"(1002) or "No connection to destination"(1001)
- **Deleting all video connections** This is a feature which could be developed.

Cheers Nico

**Comment by Nico96R** [comment]
Please response to my question so that I can close this issue or create a feature request 😄

**Comment by Nico96R** [comment]
No response yet and there is a way to delete video crosspoints.
