### ISSUE TITLE
Feedback on crosspoint change

### ISSUE THREAD

**Issue by NickMacLean** [bitfocus/companion-module-riedel-mediornet#8]
Hi, a great feature of this module would be to be able to have a feedback set from any crosspoints, not just the currently selected source or target.

This would be very useful for generating tally signals.

Cheers

**Comment by Nico96R** [comment]
Hey Nick,
Thanks for your feedback. That is a good idea. I will put it in my board. Shouldn‘t be to difficult to implement 🙂

**Comment by lundbergjohan** [comment]
Would really like this one as well. Anyway we can make this happen?

**Comment by Nico96R** [comment]
I'm currently working on an update. I hope it will be ready for the Companion 3.2 Update at the end of January.

**Comment by lundbergjohan** [comment]
That is great news. Will this also make it 7.4.0 compatible? Seems to have a few issues with feedback, variable updates etc with 7.4.0 and now realised you actually mention it is not work properly with 7.4.0.

Thanks for your great work! :)

**Comment by Nico96R** [comment]
yes, I'm currently testing 7.4.0, so everything should work after the update

**Comment by Nico96R** [comment]
The update should be in the newest beta released this night. I also found a different way to get your feedback. You could use the internal feedback "compare 2 variables" and select the input_label variable and the target_input_label and compare those. But I also added the wished feedbacks 😄
